# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-connect'
    organization: 'web-app-test'
    scannerMode: 'MSBuild'
    projectKey: 'app-test'
    projectName: 'web-app-test'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: PublishBuildArtifacts@1
